### ISSUE TITLE
Curious about the config

### ISSUE THREAD

**Issue by JasonWUCHI** [sxl142/GLoT#10]
Dear author,

Thank you for your great work! Recently I have been trying to replicate your work. I noticed that use_accel is set to False for all 3 configs provided. Should that be "True" instead (since it is mentioned in your method)?

Thank you so much.

**Comment by sxl142** [comment]
Hi, 'False' means using velocity constraint, instead of acceleration constraint. In our paper, we use the velocity constraint.

**Comment by JasonWUCHI** [comment]
Thank you!

**Comment by JasonWUCHI** [comment]
Thank you!
