### ISSUE TITLE
Inquiry about the impact of awass dataset

### ISSUE THREAD

**Issue by 1324833746** [sxl142/GLoT#4]
Hello! I noticed that VIBE uses the AWASS dataset. However, it seems that TCMR does not use it while MPS-Net does. I’m wondering if the utilization of this dataset in GLoT has a significant impact on the results?

**Comment by sxl142** [comment]
AMASS is used for GAN training in VIBE and MPS-Net, which can impose the motion prior into to the model. I think the impact may be similar to the masked pose and shape modeling and HSCR in our paper. So it may not yield a significant impact on GLOT.

**Comment by 1324833746** [comment]
Thank you for your response!
