### ISSUE TITLE
Question about training dataset in table 1

### ISSUE THREAD

**Issue by kjw9899** [sxl142/GLoT#6]
Hello author, what a great work!

Looking at repr_table1_3dpw.yaml, the datasets you used are Insta, 3DPW, Human3.6M, and 3DHP.

However, looking at your thesis, it says that you also used pennaction and posetrack as training db. I wonder what kind of training dataset you used for the 3DPW performance in table1.

**Comment by sxl142** [comment]
I used the dataset in the repr_table1_3dpw.yaml.

**Comment by kjw9899** [comment]
Then, can I understand 2D dataset you leveraged in training is only Instavariety ?

**Comment by sxl142** [comment]
Yes.

**Comment by sxl142** [comment]
> Then, can I understand 2D dataset you leveraged in training is only Instavariety ?

yes
