### ISSUE TITLE
When I was validating the model, I couldn't match the parameters. Is there a solution?

### ISSUE THREAD

**Issue by mioyeah** [sxl142/GLoT#7]
D:\tools\anaconda3\envs\GLOT2\python.exe "D:\python Project\GLoT-main\demo.py" 
Running "ffmpeg -i ./video/taiji4.mp4 -r 30000/1001 -f image2 -v error ./tmp\taiji4_mp4/%06d.jpg"
Images saved to "./tmp\taiji4_mp4"
Input video number of frames 1507

C:\Users\MIO\.torch/models/yolov3.weights
Running Multi-Person-Tracker
100%|██████████| 126/126 [01:07<00:00,  1.86it/s]
Finished. Detection + Tracking FPS 22.22
=> loaded pretrained model from './data/base_data\spin_model_checkpoint.pth.tar'
Load pretrained weights from './data/pretrained_models/table1_3dpw_weights.pth.tar'
Traceback (most recent call last):
  File "D:\python Project\GLoT-main\demo.py", line 382, in <module>
    main(args, cfgs)
  File "D:\python Project\GLoT-main\demo.py", line 118, in main
    model.load_state_dict(ckpt, strict=False)
  File "D:\tools\anaconda3\envs\GLOT2\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GLoT:
	size mismatch for regressor.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
	size mismatch for global_modeling.regressor.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).

Process finished with exit code 1

**Comment by sxl142** [comment]
'size mismatch for regressor.smpl.shapedirs'.    It seems you used the wrong SMPL parameters or the smplx version in the environment.  Please check your smplx version is 'smplx==0.1.13' and the SMPL parameters are basicModel_neutral_lbs_10_207_0_v1.0.0.pkl downloaded by our given URL.

**Comment by sxl142** [comment]
> 'size mismatch for regressor.smpl.shapedirs'. It seems you used the wrong SMPL parameters or the smplx version in the environment. Please check your smplx version is 'smplx==0.1.13' and the SMPL parameters are basicModel_neutral_lbs_10_207_0_v1.0.0.pkl downloaded by our given URL.

Download
[Download version 1.0.0 for Python 2.7 (female/male. 10 shape PCs)](https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip)
